In [1]:
import pandas as pd
from tensorflow import keras

In [2]:
df= pd.read_csv('/kaggle/input/datasets/sabitaljuma/insurence-dataset/insurance_data.csv')
df.head(10)

   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1
5   56              1                 1
6   55              0                 0
7   60              0                 1
8   62              1                 1
9   61              1                 1

# Split train and test set

In [3]:
X= df.drop('bought_insurance', axis=1)
y=df['bought_insurance']

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size= 0.2,random_state=42)

# Scaleing Data

**preprocessing: scaling the data so that both age and affordabilty in the same scale**

In [5]:
X_train_scaled= X_train.copy()
X_train_scaled['age']= X_train_scaled['age'] / 100

X_test_scaled= X_test.copy()
X_test_scaled['age']= X_test_scaled['age'] / 100

**Model Building: First we will build a model in keras/ tensorflow and see what weights and bias values comes up with. we will try to reproduce the same weights and bias in our plain python implementation of gradient descent.**

In [ ]:
# we will use one neuron, input shape 2 which is age and affordability. kernel and bias initialiser is weight and bias 
model= keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,), activation='sigmoid', kernel_initializer= 'ones', bias_initializer= 'zeros')
])

model.compile(
    optimizer= 'adam',
    loss= 'binary_crossentropy',
    metrics= ['accuracy']
)
model.fit(X_train_scaled, y_train, epochs=5000)

Epoch 1/5000

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026-09-11 00:02:59.869689: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 768ms/step - accuracy: 0.5000 - loss: 0.7428
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7424
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7420
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7416
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7411
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7407
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7403
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7399
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7395
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7390
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7386
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7382
Epoch 13/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7378
Epoch 14/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7374
Epoch 15/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7370
Epoch 16/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7366
Epoch 17/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7361
Epoch 18/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7357
Epoch 19/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7353
Epoch 20/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7349
Epoch 21/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7345
Epoch 22/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7341
Epoch 23/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7337
Epoch 24/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7333
Epoch 25/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7329
Epoch 26/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7325
Epoch 27/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7321
Epoch 28/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7317
Epoch 29/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7313
Epoch 30/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7309
Epoch 31/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7305
Epoch 32/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7301
Epoch 33/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7297
Epoch 34/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7293
Epoch 35/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7289
Epoch 36/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7285
Epoch 37/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7281
Epoch 38/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7277
Epoch 39/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7274
Epoch 40/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7270
Epoch 41/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7266
Epoch 42/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7262
Epoch 43/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7258
Epoch 44/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7254
Epoch 45/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7250
Epoch 46/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7247
Epoch 47/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7243
Epoch 48/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7239
Epoch 49/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7235
Epoch 50/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7232
Epoch 51/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7228
Epoch 52/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7224
Epoch 53/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7220
Epoch 54/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7217
Epoch 55/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7213
Epoch 56/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7209
Epoch 57/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7206
Epoch 58/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7202
Epoch 59/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7198
Epoch 60/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7195
Epoch 61/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7191
Epoch 62/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7187
Epoch 63/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7184
Epoch 64/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7180
Epoch 65/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7177
Epoch 66/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7173
Epoch 67/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7169
Epoch 68/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7166
Epoch 69/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7162
Epoch 70/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7159
Epoch 71/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7155
Epoch 72/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7152
Epoch 73/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7148
Epoch 74/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7145
Epoch 75/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7141
Epoch 76/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7138
Epoch 77/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7134
Epoch 78/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7131
Epoch 79/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7128
Epoch 80/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7124
Epoch 81/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7121
Epoch 82/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7117
Epoch 83/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7114
Epoch 84/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7111
Epoch 85/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7107
Epoch 86/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7104
Epoch 87/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7101
Epoch 88/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7097
Epoch 89/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 90/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 91/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 92/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7084
Epoch 93/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7081
Epoch 94/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7077
Epoch 95/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7074
Epoch 96/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7071
Epoch 97/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7068
Epoch 98/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7065
Epoch 99/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7061
Epoch 100/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7058
Epoch 101/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7055
Epoch 102/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7052
Epoch 103/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7049
Epoch 104/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7045
Epoch 105/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7042
Epoch 106/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7039
Epoch 107/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7036
Epoch 108/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7033
Epoch 109/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7030
Epoch 110/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7027
Epoch 111/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.7024
Epoch 112/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7021
Epoch 113/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.7018
Epoch 114/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7014
Epoch 115/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7011
Epoch 116/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7008
Epoch 117/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7005
Epoch 118/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7002
Epoch 119/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6999
Epoch 120/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6996
Epoch 121/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6993
Epoch 122/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6991
Epoch 123/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6988
Epoch 124/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6985
Epoch 125/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6982
Epoch 126/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6979
Epoch 127/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6976
Epoch 128/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6973
Epoch 129/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6970
Epoch 130/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6967
Epoch 131/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6964
Epoch 132/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6962
Epoch 133/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6959
Epoch 134/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6956
Epoch 135/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6953
Epoch 136/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6950
Epoch 137/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6947
Epoch 138/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6945
Epoch 139/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6942
Epoch 140/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6939
Epoch 141/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6936
Epoch 142/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6934
Epoch 143/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6931
Epoch 144/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6928
Epoch 145/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6925
Epoch 146/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6923
Epoch 147/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6920
Epoch 148/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6917
Epoch 149/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6915
Epoch 150/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6912
Epoch 151/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6909
Epoch 152/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6907
Epoch 153/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6904
Epoch 154/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6901
Epoch 155/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6899
Epoch 156/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6896
Epoch 157/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6894
Epoch 158/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6891
Epoch 159/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6888
Epoch 160/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6886
Epoch 161/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6883
Epoch 162/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6881
Epoch 163/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6878
Epoch 164/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6876
Epoch 165/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6873
Epoch 166/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6871
Epoch 167/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6868
Epoch 168/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6866
Epoch 169/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6863
Epoch 170/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6861
Epoch 171/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6858
Epoch 172/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6856
Epoch 173/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6853
Epoch 174/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5455 - loss: 0.6851
Epoch 175/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5455 - loss: 0.6848
Epoch 176/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.6846
Epoch 177/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5455 - loss: 0.6844
Epoch 178/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5455 - loss: 0.6841
Epoch 179/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5455 - loss: 0.6839
Epoch 180/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6836
Epoch 181/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5455 - loss: 0.6834
Epoch 182/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6832
Epoch 183/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5455 - loss: 0.6829
Epoch 184/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5455 - loss: 0.6827
Epoch 185/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5455 - loss: 0.6825
Epoch 186/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5455 - loss: 0.6822
Epoch 187/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5455 - loss: 0.6820
Epoch 188/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6818
Epoch 189/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5455 - loss: 0.6816
Epoch 190/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5455 - loss: 0.6813
Epoch 191/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6811
Epoch 192/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5455 - loss: 0.6809
Epoch 193/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5455 - loss: 0.6806
Epoch 194/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5455 - loss: 0.6804
Epoch 195/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6802
Epoch 196/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5455 - loss: 0.6800
Epoch 197/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5455 - loss: 0.6798
Epoch 198/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5455 - loss: 0.6795
Epoch 199/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5455 - loss: 0.6793
Epoch 200/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6791
Epoch 201/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5455 - loss: 0.6789
Epoch 202/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5455 - loss: 0.6787
Epoch 203/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5455 - loss: 0.6784
Epoch 204/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5455 - loss: 0.6782
Epoch 205/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5455 - loss: 0.6780
Epoch 206/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6778
Epoch 207/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6776
Epoch 208/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5455 - loss: 0.6774
Epoch 209/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5455 - loss: 0.6772
Epoch 210/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5455 - loss: 0.6770
Epoch 211/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5455 - loss: 0.6768
Epoch 212/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5455 - loss: 0.6765
Epoch 213/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5455 - loss: 0.6763
Epoch 214/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5455 - loss: 0.6761
Epoch 215/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5455 - loss: 0.6759
Epoch 216/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6757
Epoch 217/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5455 - loss: 0.6755
Epoch 218/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5455 - loss: 0.6753
Epoch 219/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6751
Epoch 220/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6749
Epoch 221/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5455 - loss: 0.6747
Epoch 222/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5455 - loss: 0.6745
Epoch 223/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5455 - loss: 0.6743
Epoch 224/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.6741
Epoch 225/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5455 - loss: 0.6739
Epoch 226/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.6737
Epoch 227/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.6735
Epoch 228/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5455 - loss: 0.6733
Epoch 229/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5455 - loss: 0.6731
Epoch 230/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5455 - loss: 0.6730
Epoch 231/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5455 - loss: 0.6728
Epoch 232/5000

> i had used epochs= 5000, then i got the accuracy: 0.9091, which is not bad at all. i think if we use more epochs it'll be better

**Evaluate the model on test set**

In [15]:
model.evaluate(X_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 1.0000 - loss: 0.2647

[0.26470303535461426, 1.0]

In [16]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

array([[0.81626713],
       [0.75767547],
       [0.8236742 ],
       [0.18819511],
       [0.38559136],
       [0.1959822 ]], dtype=float32)

In [17]:
y_test

9     1
25    1
8     1
21    0
0     0
12    0
Name: bought_insurance, dtype: int64

**Now get the value of weights and bias from the model**

In [18]:
coef, intercept= model.get_weights()
coef, intercept

(array([[5.0183096],
        [1.1966311]], dtype=float32),
 array([-2.7665412], dtype=float32))

> Here is showing w1, w2 and bias

In [19]:
import math
def sigmoid(x):
    return 1/ (1+math.exp(-x))
sigmoid(18)

0.9999999847700205

In [20]:
X_test

    age  affordibility
9    61              1
25   54              1
8    62              1
21   26              0
0    22              1
12   27              0

**Instead of model.predict, we are writing our own prediction function that uses w1, w2 and bias**

In [21]:
def predict_func(age, affordibility):
    weighted_sum= coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)
predict_func(.27, 1)

/tmp/ipykernel_58/106242007.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/ (1+math.exp(-x))

0.44646436703080217

In [22]:
predict_func(.18, 1)

/tmp/ipykernel_58/106242007.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/ (1+math.exp(-x))

0.3392553710415985

In [48]:
import numpy as np
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

**Created Log loss function**

In [49]:
def log_loss(y_true, y_predict):
    epsilon = 1e-15
    y_predict_new = [max(i,epsilon) for i in y_predict]
    y_predict_new = [min(i,1-epsilon) for i in y_predict_new]
    y_predict_new = np.array(y_predict_new)
    return -np.mean(y_true*np.log(y_predict_new)+(1-y_true)*np.log(1-y_predict_new))

# All right now comes the time to implement our final gradient descent function !! yay !!!

**im going to do it tooooo easy my friends. Donnorry!!**

In [69]:
def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias

In [70]:
gradient_descent(X_train_scaled['age'], X_train_scaled['affordibility'], y_train, 1000, 0.46)

Epoch:0, w1:0.9736899318847281, w2:0.931388810977659, bias:-0.11748951666770448, loss:0.7428288579142563
Epoch:1, w1:0.9536535852311094, w2:0.8740290167758512, bias:-0.21881533456146035, loss:0.7072146449948488
Epoch:2, w1:0.9393731039296969, w2:0.8271852202997496, bias:-0.3053620401943441, loss:0.6814881914786812
Epoch:3, w1:0.9301932588998061, w2:0.7897792032048467, bias:-0.37884372361582785, loss:0.6633428084673968
Epoch:4, w1:0.9254091137248938, w2:0.7605726653866934, bias:-0.44108236820018304, loss:0.650742850709519
Epoch:5, w1:0.9243325693598607, w2:0.738313053647322, bias:-0.49384257986251556, loss:0.6420508089402462
Epoch:6, w1:0.926333296357235, w2:0.7218280753843739, bias:-0.5387319906498417, loss:0.6360356979531208
Epoch:7, w1:0.930858097563688, w2:0.7100747303660235, bias:-0.5771558825717441, loss:0.631816485354411
Epoch:8, w1:0.9374354910317362, w2:0.7021560855322683, bias:-0.6103083840841516, loss:0.6287844495353145
Epoch:9, w1:0.9456716791005845, w2:0.6973185496313956, bias:-0.639184616298235, loss:0.626529442944178
Epoch:10, w1:0.9552423303850909, w2:0.6949390905593646, bias:-0.6646027475198829, loss:0.624779988185889
Epoch:11, w1:0.9658829303208043, w2:0.6945084189034805, bias:-0.6872291753319572, loss:0.6233586375123873
Epoch:12, w1:0.9773792291739571, w2:0.6956135754890374, bias:-0.7076031311561145, loss:0.6221504235399642
Epoch:13, w1:0.9895585317325278, w2:0.6979216736079811, bias:-0.7261589451808116, loss:0.6210813136963943
Epoch:14, w1:1.0022821152183012, w2:0.7011655439884263, bias:-0.7432453293938631, loss:0.6201038296955017
Epoch:15, w1:1.0154388156305512, w2:0.7051314781630986, bias:-0.7591416308217254, loss:0.6191875984155962
Epoch:16, w1:1.02893970239324, w2:0.709648985803042, bias:-0.7740712914557775, loss:0.6183132103318709
Epoch:17, w1:1.0427137116001346, w2:0.7145823568137355, bias:-0.7882128634885648, loss:0.6174682582697213
Epoch:18, w1:1.0567040961203982, w2:0.7198237783231305, bias:-0.8017089504235339, loss:0.616644796399796
Epoch:19, w1:1.070865557308088, w2:0.7252877588356242, bias:-0.8146734229312049, loss:0.61583771667916
Epoch:20, w1:1.0851619375646322, w2:0.7309066337223022, bias:-0.827197218409105, loss:0.6150437144364911
Epoch:21, w1:1.0995643699866926, w2:0.7366269554469955, bias:-0.8393529883341466, loss:0.6142606306676933
Epoch:22, w1:1.1140497980199757, w2:0.7424066021061672, bias:-0.8511988141914534, loss:0.6134870344622743
Epoch:23, w1:1.128599793177434, w2:0.7482124659467998, bias:-0.8627811738792539, loss:0.6127219581535038
Epoch:24, w1:1.1431996120187127, w2:0.7540186082823848, bias:-0.8741373069609975, loss:0.6119647294414037
Epoch:25, w1:1.1578374446869286, w2:0.7598047883543967, bias:-0.8852970989389227, loss:0.6112148650157284
Epoch:26, w1:1.1725038165119066, w2:0.7655552913481779, bias:-0.8962845813945609, loss:0.6104720031489476
Epoch:27, w1:1.1871911117453238, w2:0.771257995332388, bias:-0.9071191257544718, loss:0.6097358609684286
Epoch:28, w1:1.2018931946388467, w2:0.7769036287786945, bias:-0.9178163929444821, loss:0.6090062073517919
Epoch:29, w1:1.2166051080444702, w2:0.7824851799565414, bias:-0.9283890886873851, loss:0.608282845710547
Epoch:30, w1:1.2313228337147435, w2:0.7879974272726736, bias:-0.9388475641432381, loss:0.6075656030320272
Epoch:31, w1:1.2460431016880735, w2:0.7934365658732724, bias:-0.9492002935318158, loss:0.6068543228826871
Epoch:32, w1:1.26076323871096, w2:0.7987999108337119, bias:-0.9594542539318721, loss:0.606148860919597
Epoch:33, w1:1.275481047699055, w2:0.8040856612650232, bias:-0.9696152273069788, loss:0.6054490819908689
Epoch:34, w1:1.290194711874047, w2:0.8092927128629349, bias:-0.9796880407059236, loss:0.6047548582434892
Epoch:35, w1:1.3049027185161206, w2:0.8144205089744891, bias:-0.9896767573186839, loss:0.6040660678706471
Epoch:36, w1:1.319603798308875, w2:0.8194689222880241, bias:-0.9995848284688316, loss:0.6033825942657642
Epoch:37, w1:1.334296877078748, w2:0.8244381608690347, bias:-1.00941521455492, loss:0.6027043254358909
Epoch:38, w1:1.34898103738721, w2:0.8293286935508274, bias:-1.0191704813088125, loss:0.6020311535811719
Epoch:39, w1:1.3636554879557021, w2:0.8341411907120669, bias:-1.0288528764316198, loss:0.6013629747812914
Epoch:40, w1:1.3783195393179468, w2:0.8388764772868943, bias:-1.0384643906289521, loss:0.6006996887514325
Epoch:41, w1:1.3929725844237946, w2:0.8435354955001086, bias:-1.048006806241578, loss:0.6000411986439697
Epoch:42, w1:1.407614083180624, w2:0.8481192753340512, bias:-1.057481736011579, loss:0.5993874108807854
Epoch:43, w1:1.4222435501263797, w2:0.8526289111424994, bias:-1.066890654002851, loss:0.5987382350065792
Epoch:44, w1:1.4368605445936515, w2:0.8570655431517031, bias:-1.0762349202806512, loss:0.598093583557015
Epoch:45, w1:1.4514646628555743, w2:0.8614303428468635, bias:-1.0855158006258134, loss:0.5974533719377464
Epoch:46, w1:1.4660555318487032, w2:0.8657245014475712, bias:-1.0947344822977763, loss:0.5968175183117647
Epoch:47, w1:1.4806328041509815, w2:0.8699492208388353, bias:-1.103892086652756, loss:0.5961859434933902
Epoch:48, w1:1.49519615395884, w2:0.8741057064540038, bias:-1.1129896792582663, loss:0.5955585708477928
Epoch:49, w1:1.5097452738598662, w2:0.8781951617089659, bias:-1.1220282780139241, loss:0.5949353261952894
Epoch:50, w1:1.524279872239132, w2:0.8822187836689879, bias:-1.1310088596841466, loss:0.5943161377198863
Epoch:51, w1:1.5387996711903813, w2:0.8861777596947031, bias:-1.139932365165402, loss:0.5937009358816897
Epoch:52, w1:1.5533044048295999, w2:0.8900732648656111, bias:-1.1487997037447355, loss:0.5930896533328961
Epoch:53, w1:1.567793817929426, w2:0.893906460020651, bias:-1.1576117565538497, loss:0.5924822248371355
Epoch:54, w1:1.582267664809504, w2:0.8976784902882078, bias:-1.1663693793813252, loss:0.5918785871919885
Epoch:55, w1:1.5967257084311235, w2:0.9013904840039859, bias:-1.175073404972397, loss:0.5912786791545124
Epoch:56, w1:1.6111677196550176, w2:0.9050435519359376, bias:-1.183724644919323, loss:0.5906824413696463
Epoch:57, w1:1.6255934766295705, w2:0.9086387867519404, bias:-1.1923238912243923, loss:0.5900898163013605
Epoch:58, w1:1.6400027642833535, w2:0.9121772626790609, bias:-1.2008719176009222, loss:0.5895007481664456
Epoch:59, w1:1.654395373901209, w2:0.9156600353136914, bias:-1.2093694805643016, loss:0.5889151828708239
Epoch:60, w1:1.6687711027673289, w2:0.9190881415501766, bias:-1.2178173203545684, loss:0.5883330679482884
Epoch:61, w1:1.6831297538621286, w2:0.9224625996021639, bias:-1.226216161723583, loss:0.5877543525015689
Epoch:62, w1:1.6974711356023962, w2:0.9257844090961931, bias:-1.2345667146131625, loss:0.5871789871456384
Epoch:63, w1:1.7117950616163273, w2:0.9290545512212334, bias:-1.2428696747452048, loss:0.5866069239531645
Epoch:64, w1:1.726101350546749, w2:0.9322739889212249, bias:-1.2511257241405795, loss:0.5860381164020316
Epoch:65, w1:1.74038982587719, w2:0.9354436671203415, bias:-1.2593355315801789, loss:0.5854725193248442
Epoch:66, w1:1.7546603157765295, w2:0.9385645129728112, bias:-1.2674997530188292, loss:0.5849100888603412
Epoch:67, w1:1.7689126529588146, w2:0.9416374361308231, bias:-1.275619031960611, loss:0.5843507824066418
Epoch:68, w1:1.7831466745555187, w2:0.9446633290253915, bias:-1.283693999802426, loss:0.5837945585762572
Epoch:69, w1:1.7973622219980596, w2:0.9476430671561192, bias:-1.2917252761512859, loss:0.5832413771527942
Epoch:70, w1:1.8115591409088299, w2:0.9505775093866566, bias:-1.2997134691197103, loss:0.5826911990492895
Epoch:71, w1:1.8257372809993349, w2:0.9534674982433321, bias:-1.3076591756027507, loss:0.5821439862681095
Epoch:72, w1:1.839896495974317, w2:0.9563138602149697, bias:-1.3155629815394705, loss:0.5815997018623559
Epoch:73, w1:1.8540366434409572, w2:0.9591174060523414, bias:-1.3234254621611543, loss:0.5810583098987187
Epoch:74, w1:1.8681575848224266, w2:0.9618789310660443, bias:-1.3312471822280851, loss:0.58051977542172
Epoch:75, w1:1.8822591852751982, w2:0.9645992154218651, bias:-1.3390286962563693, loss:0.579984064419297
Epoch:76, w1:1.8963413136096434, w2:0.9672790244329128, bias:-1.3467705487360144, loss:0.5794511437896713
Epoch:77, w1:1.9104038422135234, w2:0.969919108847971, bias:-1.354473274341238, loss:0.5789209813094535
Epoch:78, w1:1.9244466469780626, w2:0.9725202051356608, bias:-1.3621373981338052, loss:0.5783935456029389
Epoch:79, w1:1.9384696072263448, w2:0.9750830357641131, bias:-1.3697634357600514, loss:0.5778688061125461
Epoch:80, w1:1.9524726056438206, w2:0.9776083094759327, bias:-1.3773518936421296, loss:0.5773467330703558
Epoch:81, w1:1.9664555282107488, w2:0.9800967215583106, bias:-1.3849032691639303, loss:0.5768272974707069
Epoch:82, w1:1.9804182641364287, w2:0.9825489541081904, bias:-1.392418050852049, loss:0.5763104710438095
Epoch:83, w1:1.9943607057950992, w2:0.9849656762924377, bias:-1.3998967185521152, loss:0.5757962262303377
Epoch:84, w1:2.008282748663402, w2:0.9873475446029975, bias:-1.4073397436007509, loss:0.5752845361569595
Epoch:85, w1:2.022184291259321, w2:0.9896952031070477, bias:-1.4147475889933847, loss:0.574775374612777
Epoch:86, w1:2.0360652350825252, w2:0.99200928369218, bias:-1.422120709548121, loss:0.5742687160266319
Epoch:87, w1:2.049925484556046, w2:0.9942904063066522, bias:-1.429459552065836, loss:0.5737645354452513
Epoch:88, w1:2.0637649469692336, w2:0.9965391791947715, bias:-1.4367645554866506, loss:0.5732628085121987
Epoch:89, w1:2.077583532421944, w2:0.998756199127475, bias:-1.4440361510429165, loss:0.5727635114475975
Epoch:90, w1:2.0913811537699094, w2:1.0009420516281817, bias:-1.4512747624088354, loss:0.5722666210286019
Epoch:91, w1:2.105157726571251, w2:1.003097311193995, bias:-1.458480805846823, loss:0.5717721145705856
Epoch:92, w1:2.1189131690341005, w2:1.0052225415123381, bias:-1.4656546903507157, loss:0.571279969909017
Epoch:93, w1:2.1326474019652957, w2:1.007318295673109, bias:-1.472796817785915, loss:0.570790165382002
Epoch:94, w1:2.146360348720115, w2:1.0093851163764382, bias:-1.4799075830265551, loss:0.5703026798134626
Epoch:95, w1:2.160051935153028, w2:1.0114235361361412, bias:-1.4869873740897748, loss:0.5698174924969315
Epoch:96, w1:2.1737220895694316, w2:1.0134340774789485, bias:-1.4940365722671685, loss:0.5693345831799377
Epoch:97, w1:2.187370742678347, w2:1.0154172531396048, bias:-1.5010555522534914, loss:0.5688539320489616
Epoch:98, w1:2.2009978275460518, w2:1.0173735662519205, bias:-1.5080446822726845, loss:0.5683755197149363
Epoch:99, w1:2.2146032795506274, w2:1.0193035105358637, bias:-1.515004324201286, loss:0.5678993271992777
Epoch:100, w1:2.2281870363373972, w2:1.021207570480777, bias:-1.5219348336892933, loss:0.5674253359204207
Epoch:101, w1:2.2417490377752345, w2:1.0230862215248024, bias:-1.5288365602785345, loss:0.5669535276808445
Epoch:102, w1:2.255289225913722, w2:1.0249399302305953, bias:-1.5357098475186088, loss:0.5664838846545661
Epoch:103, w1:2.26880754494114, w2:1.0267691544574107, bias:-1.5425550330804503, loss:0.5660163893750885
Epoch:104, w1:2.2823039411432697, w2:1.0285743435296395, bias:-1.5493724488675729, loss:0.5655510247237828
Epoch:105, w1:2.2957783628629866, w2:1.030355938401873, bias:-1.5561624211250464, loss:0.5650877739186891
Epoch:106, w1:2.309230760460632, w2:1.0321143718205703, bias:-1.562925270546257, loss:0.564626620503722
Epoch:107, w1:2.322661086275144, w2:1.0338500684824057, bias:-1.5696613123774994, loss:0.5641675483382641
Epoch:108, w1:2.33606929458593, w2:1.035563445189367, bias:-1.5763708565204524, loss:0.563710541587133
Epoch:109, w1:2.349455341575465, w2:1.0372549110006768, bias:-1.583054207632583, loss:0.5632555847109085
Epoch:110, w1:2.362819185292602, w2:1.0389248673816067, bias:-1.5897116652255254, loss:0.5628026624566079
Epoch:111, w1:2.3761607856165785, w2:1.040573708349253, bias:-1.5963435237614785, loss:0.562351759848693
Epoch:112, w1:2.3894801042217004, w2:1.0422018206153387, bias:-1.602950072747668, loss:0.5619028621803996
Epoch:113, w1:2.4027771045426967, w2:1.04380958372611, bias:-1.6095315968289134, loss:0.5614559550053765
Epoch:114, w1:2.4160517517407225, w2:1.0453973701993888, bias:-1.6160883758783424, loss:0.5610110241296223
Epoch:115, w1:2.4293040126700043, w2:1.0469655456588438, bias:-1.622620685086291, loss:0.5605680556037097
Epoch:116, w1:2.4425338558451064, w2:1.0485144689655421, bias:-1.629128795047433, loss:0.5601270357152859
Epoch:117, w1:2.4557412514088135, w2:1.0500444923468393, bias:-1.635612971846172, loss:0.559687950981839
Epoch:118, w1:2.4689261711006107, w2:1.051555961522667, bias:-1.6420734771403382, loss:0.5592507881437215
Epoch:119, w1:2.482088588225752, w2:1.0530492158292744, bias:-1.6485105682432226, loss:0.5588155341574205
Epoch:120, w1:2.4952284776249023, w2:1.0545245883404786, bias:-1.654924498203987, loss:0.5583821761890648
Epoch:121, w1:2.5083458156443443, w2:1.0559824059864795, bias:-1.6613155158864843, loss:0.557950701608164
Epoch:122, w1:2.521440580106737, w2:1.0574229896702896, bias:-1.6676838660465216, loss:0.5575210979815646
Epoch:123, w1:2.534512750282415, w2:1.0588466543818318, bias:-1.6740297894076015, loss:0.5570933530676219
Epoch:124, w1:2.5475623068612183, w2:1.0602537093097566, bias:-1.6803535227351711, loss:0.5566674548105743
Epoch:125, w1:2.5605892319248382, w2:1.0616444579510256, bias:-1.686655298909415, loss:0.5562433913351179
Epoch:126, w1:2.5735935089196764, w2:1.0630191982183106, bias:-1.6929353469966173, loss:0.5558211509411678
Epoch:127, w1:2.586575122630199, w2:1.0643782225452558, bias:-1.6991938923191288, loss:0.5554007220988053
Epoch:128, w1:2.5995340591527825, w2:1.0657218179896482, bias:-1.7054311565239644, loss:0.5549820934434008
Epoch:129, w1:2.612470305870034, w2:1.0670502663345407, bias:-1.7116473576500615, loss:0.5545652537709059
Epoch:130, w1:2.6253838514255854, w2:1.068363844187373, bias:-1.717842710194228, loss:0.5541501920333112
Epoch:131, w1:2.6382746856993453, w2:1.0696628230771317, bias:-1.724017425175806, loss:0.5537368973342596
Epoch:132, w1:2.6511427997832024, w2:1.0709474695495913, bias:-1.7301717102000798, loss:0.5533253589248148
Epoch:133, w1:2.6639881859571712, w2:1.0722180452606795, bias:-1.7363057695204518, loss:0.5529155661993732
Epoch:134, w1:2.676810837665972, w2:1.0734748070680025, bias:-1.7424198040994154, loss:0.5525075086917203
Epoch:135, w1:2.689610749496034, w2:1.0747180071205722, bias:-1.7485140116683477, loss:0.5521011760712203
Epoch:136, w1:2.702387917152919, w2:1.0759478929467725, bias:-1.7545885867861466, loss:0.5516965581391399
Epoch:137, w1:2.7151423374391475, w2:1.0771647075406028, bias:-1.7606437208967372, loss:0.5512936448250959
Epoch:138, w1:2.727874008232434, w2:1.0783686894462319, bias:-1.7666796023854698, loss:0.5508924261836268
Epoch:139, w1:2.7405829284643093, w2:1.0795600728409025, bias:-1.7726964166344346, loss:0.5504928923908812
Epoch:140, w1:2.753269098099129, w2:1.0807390876162168, bias:-1.7786943460767113, loss:0.5500950337414183
Epoch:141, w1:2.765932518113463, w2:1.0819059594578393, bias:-1.7846735702495808, loss:0.549698840645121
Epoch:142, w1:2.7785731904758553, w2:1.0830609099236488, bias:-1.7906342658467151, loss:0.54930430362421
Epoch:143, w1:2.7911911181269446, w2:1.0842041565203735, bias:-1.7965766067693705, loss:0.5489114133103622
Epoch:144, w1:2.8037863049599467, w2:1.085335912778739, bias:-1.802500764176602, loss:0.5485201604419263
Epoch:145, w1:2.816358755801483, w2:1.0864563883271607, bias:-1.8084069065345199, loss:0.5481305358612326
Epoch:146, w1:2.8289084763927552, w2:1.087565788964012, bias:-1.8142951996646075, loss:0.5477425305119938
Epoch:147, w1:2.8414354733710567, w2:1.088664316728495, bias:-1.8201658067911204, loss:0.5473561354367932
Epoch:148, w1:2.8539397542516136, w2:1.0897521699701465, bias:-1.8260188885875834, loss:0.5469713417746572
Epoch:149, w1:2.866421327409753, w2:1.0908295434170034, bias:-1.8318546032224061, loss:0.5465881407587113
Epoch:150, w1:2.8788802020633866, w2:1.0918966282424585, bias:-1.8376731064036336, loss:0.5462065237139112
Epoch:151, w1:2.891316388255809, w2:1.0929536121308303, bias:-1.8434745514228494, loss:0.5458264820548531
Epoch:152, w1:2.903729896838803, w2:1.0940006793416772, bias:-1.8492590891982492, loss:0.5454480072836544
Epoch:153, w1:2.916120739456045, w2:1.0950380107728777, bias:-1.8550268683168998, loss:0.5450710909879073
Epoch:154, w1:2.9284889285268068, w2:1.0960657840225045, bias:-1.8607780350762022, loss:0.5446957248386981
Epoch:155, w1:2.9408344772299464, w2:1.0970841734495165, bias:-1.866512733524573, loss:0.5443219005886926
Epoch:156, w1:2.953157399488185, w2:1.0980933502332917, bias:-1.8722311055013598, loss:0.5439496100702871
Epoch:157, w1:2.9654577099526627, w2:1.0990934824320266, bias:-1.8779332906760073, loss:0.5435788451938158
Epoch:158, w1:2.977735423987769, w2:1.1000847350400225, bias:-1.8836194265864876, loss:0.5432095979458211
Epoch:159, w1:2.9899905576562413, w2:1.1010672700438837, bias:-1.8892896486770099, loss:0.5428418603873787
Epoch:160, w1:3.002223127704531, w2:1.1020412464776486, bias:-1.8949440903350232, loss:0.5424756246524773
Epoch:161, w1:3.0144331515484253, w2:1.1030068204768737, bias:-1.9005828829275286, loss:0.5421108829464516
Epoch:162, w1:3.026620647258927, w2:1.1039641453316948, bias:-1.9062061558367112, loss:0.5417476275444663
Epoch:163, w1:3.038785633548384, w2:1.1049133715388832, bias:-1.9118140364949066, loss:0.5413858507900478
Epoch:164, w1:3.050928129756862, w2:1.105854646852918, bias:-1.9174066504189173, loss:0.5410255450936652
Epoch:165, w1:3.063048155838763, w2:1.1067881163360949, bias:-1.9229841212436882, loss:0.5406667029313558
Epoch:166, w1:3.0751457323496774, w2:1.1077139224076888, bias:-1.9285465707553557, loss:0.5403093168433944
Epoch:167, w1:3.087220880433469, w2:1.1086322048921928, bias:-1.9340941189236835, loss:0.5399533794330067
Epoch:168, w1:3.099273621809591, w2:1.1095431010666466, bias:-1.9396268839338946, loss:0.5395988833651209
Epoch:169, w1:3.1113039787606236, w2:1.1104467457070775, bias:-1.9451449822179139, loss:0.5392458213651614
Epoch:170, w1:3.1233119741200333, w2:1.111343271134069, bias:-1.950648528485032, loss:0.5388941862178795
Epoch:171, w1:3.1352976312601486, w2:1.1122328072574743, bias:-1.9561376357520004, loss:0.5385439707662217
Epoch:172, w1:3.1472609740803494, w2:1.1131154816202935, bias:-1.9616124153725711, loss:0.5381951679102319
Epoch:173, w1:3.159202026995462, w2:1.1139914194417277, bias:-1.96707297706649, loss:0.5378477706059898
Epoch:174, w1:3.171120814924363, w2:1.1148607436594298, bias:-1.9725194289479553, loss:0.5375017718645813
Epoch:175, w1:3.1830173632787826, w2:1.1157235749709653, bias:-1.9779518775535507, loss:0.5371571647511
Epoch:176, w1:3.1948916979523054, w2:1.1165800318745003, bias:-1.9833704278696656, loss:0.5368139423836822
Epoch:177, w1:3.206743845309568, w2:1.1174302307087307, bias:-1.9887751833594083, loss:0.536472097932569
Epoch:178, w1:3.218573832175644, w2:1.1182742856920675, bias:-1.9941662459890268, loss:0.5361316246191975
Epoch:179, w1:3.23038168582562, w2:1.1191123089610944, bias:-1.9995437162538428, loss:0.5357925157153212
Epoch:180, w1:3.242167433974353, w2:1.119944410608309, bias:-2.0049076932037093, loss:0.5354547645421551
Epoch:181, w1:3.2539311047664135, w2:1.1207706987191641, bias:-2.010258274468004, loss:0.5351183644695484
Epoch:182, w1:3.2656727267661982, w2:1.121591279408423, bias:-2.015595556280162, loss:0.5347833089151804
Epoch:183, w1:3.2773923289482267, w2:1.1224062568558384, bias:-2.020919633501761, loss:0.5344495913437822
Epoch:184, w1:3.289089940687604, w2:1.123215733341173, bias:-2.0262305996461647, loss:0.5341172052663793
Epoch:185, w1:3.3007655917506535, w2:1.124019809278571, bias:-2.0315285469017375, loss:0.5337861442395591
Epoch:186, w1:3.3124193122857153, w2:1.1248185832502948, bias:-2.0368135661546316, loss:0.5334564018647581
Epoch:187, w1:3.3240511328141085, w2:1.1256121520398386, bias:-2.0420857470111606, loss:0.533127971787571
Epoch:188, w1:3.335661084221251, w2:1.1264006106644302, bias:-2.0473451778197655, loss:0.5328008476970791

(np.float64(6.9617150533861984),
 np.float64(1.3673304404593587),
 np.float64(-3.6920983113989734))

In [54]:
coef, intercept

(array([[5.0183096],
        [1.1966311]], dtype=float32),
 array([-2.7665412], dtype=float32))

**This shows that in the end we were able to come up with almost same value of w1,w2 and bias using a plain python implementation of gradient descent function**